module.exports = {
    INTERNAL_ERROR: 0,
    DUPLICATED_USER: 100,
    INCORRECT_USER_OR_PASSWORD: 200,
    INCORRECT_TOKEN: 300,
    PASSWORD_DO_NOT_MATCH: 400,
    USER_NOT_FOUND: 500,
    ACCOUNT_NOT_FOUND: 600,
    GROUP_NOT_FOUND: 700,
    EMAIL_NOT_CONFIRMED: 800,
    INCORRECT_REQUEST: 900,
    EMAIL_ALLREADY_CONFIRMED: 1000,
    TOKEN_HAS_EXPIRED: 1100,
}
