module.exports = {
    ACCOUNT_SUCCESSFULLY_CREATED: 100,
    ACCOUNT_SUCCESSFULLY_MODIFIED: 200,
    ACCOUNT_SUCCESSFULLY_DELETED: 300,
    GROUP_SUCCESSFULLY_CREATED: 110,
    GROUP_SUCCESSFULLY_MODIFIED: 210,
    GROUP_SUCCESSFULLY_DELETED: 310,
    USER_SUCCESSFULLY_CREATED: 120,
    USER_SUCCESSFULLY_MODIFIED: 220,
    USER_SUCCESSFULLY_DELETED: 320,
    PASSWORD_SUCCESSFULLY_CHANGED: 400,
}
